version: '3.3'


services:
    mongodb:
        image: mongo:latest

    comments:
        build: './comments'
        volumes: 
            - ./comments:/go/src/github.com/minhajuddinkhan/reviewzone/comments

    dump:
        build: './dump'
        volumes: 
            - ./dump:/go/src/github.com/minhajuddinkhan/reviewzone/dump

    reviewer:
        build: './reviewer'
        volumes: 
            - ./reviewer:/go/src/github.com/minhajuddinkhan/reviewzone/reviewer
    api:
        build: '.'
        volumes:
          - .:/go/src/github.com/minhajuddinkhan/reviewzone 
        depends_on:
            - comments
            - dump
            - reviewer
            - mongodb
        ports:
            - 6000:6000