version: '3.3'


services:
    mongodb:
        image: mongo:latest

    comments:
        build: './comments'
        ports:
            - 3000:3000

        volumes: 
            - ./comments:/go/src/github.com/minhajuddinkhan/reviewzone/comments

    dump:
        build: './dump'
        ports:
            - 4000:4000
        volumes: 
            - ./dump:/go/src/github.com/minhajuddinkhan/reviewzone/dump
 
    reviewer:
        build: './reviewer'
        volumes: 
            - ./reviewer:/go/src/github.com/minhajuddinkhan/reviewzone/reviewer
        ports:
            - 5000:5000

    api:
        build: '.'
        depends_on:
            - comments
            - dump
            - reviewer
            - mongodb
        ports:
            - 6000:6000